version: '3'

services:
  laravel-app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: comments_spa
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    links:
      - database
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - default
    depends_on:
      - database